---
- name: HAProxy configuration | Update config file
  ansible.builtin.template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0640'
    validate: 'haproxy -f %s -c'
  notify: restart haproxy

- name: HAProxy configuration | Format file by removing empty lines
  ansible.builtin.lineinfile:
    path: /etc/haproxy/haproxy.cfg
    regex: '^\n'
    state: absent

- name: HAProxy configuration | Format file by adding one empty line before each section
  ansible.builtin.replace:
    dest: /etc/haproxy/haproxy.cfg
    regexp: "^#--#"
    replace: ""
