---
- name: HAProxy | Import install task
  ansible.builtin.import_tasks: install.yml

- name: HAProxy | Import pre_tasks task
  ansible.builtin.import_tasks: pre_tasks.yml

- name: HAProxy | Import certificates task
  ansible.builtin.import_tasks: certificates.yml

- name: HAProxy | Import static ACL task
  ansible.builtin.import_tasks: acl.yml
  when: haproxy_acl_files | length > 0

- name: HAProxy | Import configuration task
  ansible.builtin.import_tasks: configuration.yml

- name: HAProxy | Start and enable the service
  ansible.builtin.service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
