---
- name: HAProxy Pre-tasks | Make /var/www dir
  ansible.builtin.file:
    path: /var/www
    state: directory
    mode: '0755'

- name: HAProxy Pre-tasks | Copy HAProxy 403
  ansible.builtin.copy:
    src: "{{ haproxy_403_file }}"
    dest: /var/www/403.http
    owner: root
    group: haproxy
    mode: '0644'
